
run:
  concurrency: 4
  timeout: 20m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - .github
    - bin
    - examples
    - nuget
    - venv
  skip-dirs-use-default: true
  allow-parallel-runners: false
output:
  format: tab
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: false
linters:
  disable-all: false
  enable:
    - asasalint
    - bidichk
    - decorder
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - forbidigo
    - gci
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - gosimple
    - gosec
    - govet
    - grouper
    - importas
    - interfacebloat
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilnil
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - usestdlibvars
    - unparam
    - whitespace
  fast: false
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/pulumiverse/pulumi-esxi-native/provider)
      - blank
    skip-generated: true
    custom-order: true
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID", "API", "URL", "JSON", "IP", "HTTP", "CPU"] # AllowList
  stylecheck:
    checks:
      - "all"
      - "-ST1003"